[BE #99] Interceptor
codesquad-member-2020/airbnb-11 pull request #128
Opened 2020-06-04 09:56 UTC by 102092

- 기본적인 인터셉터를 구현하였습니다.
- `/reservations/**`  로 매칭되는 요청에 작동하도록 설정했습니다.
- 우선 쿠키에서 jwt를 가져오는 로직만 작성했습니다.
- 현재 `RoomRestControllerTest` 를 통과하지 못하고 있습니다.
  - ReservationInterceptor bean을 만들 때, @Autowired되는 `Service`들이 없어서 발생하는 문제 인듯 한데, 한번 봐주시면 감사하겠습니당.. 저도 좀 더 찾아볼 생각입니다.
- 껍데기 기능만 만든 만큼, 필요하거나 혹은 이상한 부분 알려주시면 수정해보도록 하겠습니다~

2020-06-04 10:12 UTC, ksundong commented
일단 reservation만 작동되게 하면 안된다고 생각해요.
왜냐면 room에서 예약 등록하는 것도 있거든요.

2020-06-04 10:31 UTC, ksundong commented
코드 보고있는데 인터셉터가 컨트롤러 패키지에 있는 것은 좀 이상해보입니다!

2020-06-04 10:33 UTC, ksundong commented
`@ContextConfiguration(classes = { JwtService.class })`
이렇게 넣으면 JwtService도 Bean으로 가져올 수 있습니다.

2020-06-04 11:26 UTC, ksundong requested changes
고생하셨어요! 수정요청 드립니다!

2020-06-04 11:26 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/common/config/WebConfig.java
> +        .addPathPatterns("/reservations/**");
이부분 한 번만 더 고민해주세요.
Reservation에서만 체크하면 될까요?
room에서도 예약기능이 있습니다.

2020-06-04 11:26 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/controller/ReservationInterceptor.java
> +  private static Logger log = LoggerFactory.getLogger(ReservationInterceptor.class);
Logger가 final이 아니네요. 확인해주세요.

2020-06-04 11:26 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/controller/ReservationInterceptor.java
> +  private LoginService loginService;
Constructor Injection을 사용해주세요!

2020-06-04 11:26 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/controller/ReservationInterceptor.java
> +    String token = "";
왜 토큰이 하드코딩 되어있을까용??

2020-06-04 11:26 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/controller/ReservationInterceptor.java
> +
메소드 도입부가 빈 줄로 시작하나용??

2020-06-04 11:26 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/controller/ReservationInterceptor.java
> +    String token = "";
그냥 초기화 없이 사용하는게 깔끔할 것 같네요!

2020-06-04 11:26 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/controller/ReservationInterceptor.java
> +    }
다른 쿠키가 들어있으면 어떡하죠?

2020-06-04 11:26 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/controller/ReservationInterceptor.java
> +    }
그리고 `throw new LoginRequiredException();` 도 사용하면 좋습니다.

2020-06-04 11:26 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/controller/ReservationInterceptor.java
> +    }
함수형을 적용해보는건 어떨까 싶어서 써봤는데 성능이 구릴 것 같네요.
```suggestion
    String token = Arrays.stream(cookies)
        .filter(c -> c.getName().equals("jwt"))
        .map(Cookie::getValue)
        .reduce(String::concat)
        .orElse("");
```

2020-06-04 11:26 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/controller/ReservationInterceptor.java
> +    return false;
```suggestion
    return loginService.findUserByEmail(user);
```
메소드 명은 좀 바꾸는게 좋을 것 같네요.
뭔가 boolean 타입이 올 것 같은 네이밍은 아닌 것 같아요.

2020-06-04 11:26 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/domain/user/UserRepository.java
> +@Repository
여기에 Repository를 붙여줘야하나용?
https://stackoverflow.com/questions/42691697/using-repository-annotation-when-implementing-jparepostiory-in-spring
참고해보세요!

2020-06-04 11:26 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/service/LoginService.java
> +    headers.setLocation(URI.create("http://" + host + "/"));
이러면 배포되었을 때, api로 가요! 확인 부탁드릴게요!

2020-06-04 11:26 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/service/LoginService.java
> +  }
메소드 명 변경해주세요~

2020-06-04 12:18 UTC, 102092 commented on BE/src/main/java/kr/codesquad/airbnb11/common/config/WebConfig.java
> +        .addPathPatterns("/reservations/**");
그렇군요 알려주셔서 감사합니다!!

2020-06-04 12:51 UTC, 102092 commented on BE/src/main/java/kr/codesquad/airbnb11/controller/ReservationInterceptor.java
> +  private LoginService loginService;
넵넵 클래스 분리를 통해서 해결할 생각입니다

2020-06-04 12:51 UTC, 102092 commented on BE/src/main/java/kr/codesquad/airbnb11/controller/ReservationInterceptor.java
> +
자동정렬하다보니까, 그렇게 되었네요.. 수정하겠습니다~!

2020-06-04 12:53 UTC, 102092 commented on BE/src/main/java/kr/codesquad/airbnb11/controller/ReservationInterceptor.java
> +    }
함수형으로 바꾸는게 좀 더 보기 편한것 같아요 바꾸겠습니당!!

2020-06-04 12:58 UTC, 102092 commented on BE/src/main/java/kr/codesquad/airbnb11/controller/ReservationInterceptor.java
> +    return false;
isUserExist 또는 isValidUser 생각중인데 어떤게 괜찮을까요?

2020-06-04 13:03 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/controller/ReservationInterceptor.java
> +  private LoginService loginService;
클래스 분리 말씀이신가용?? 어떻게 하실지 기대되네요!

2020-06-04 13:03 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/controller/ReservationInterceptor.java
> +
넵넵!

2020-06-04 13:04 UTC, 102092 commented on BE/src/main/java/kr/codesquad/airbnb11/service/LoginService.java
> +    headers.setLocation(URI.create("http://" + host + "/"));
yml에 필드를 하나 더 추가해서 해결하려 합니다~

2020-06-04 13:04 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/controller/ReservationInterceptor.java
> +    }
아 성능이 안좋아요 ㅋㅋㅋㅋㅋㅋ 그냥 써본거에요!

2020-06-04 13:04 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/controller/ReservationInterceptor.java
> +    return false;
exist가 낫겠네요!

2020-06-04 13:36 UTC, 102092 commented
테스트 실패합니다
interceptor를 어떻게 test에서 제외시키거나, 옵션을 추가해야할지 잘 모르겠네요..
내일 한번 얘기해보면 좋을듯 합니다.

2020-06-04 14:00 UTC, ksundong requested changes
고생하셨어요! 고쳐주세요!

2020-06-04 14:00 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/common/config/WebConfig.java
> +
빈 라인이 들어갔네요.

2020-06-04 14:00 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/common/config/IntercepterConfig.java
> +}
별도 Config로 빼는것도 나쁘진 않은데, Interceptor가 Web Configurer에 속하는 것도 맞죠.

2020-06-04 14:00 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/common/security/ReservationInterceptor.java
> +  private final LoginService loginService;
서로 붙여줘도 될 것 같네요.

2020-06-04 14:00 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/common/security/ReservationInterceptor.java
> +      LoginService loginService) {
이건 한 줄 로도 될 것 같은데 확인한 번 부탁드릴게요!

2020-06-04 14:00 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/common/security/ReservationInterceptor.java
> +  }
```suggestion
    return loginService.isUserExist(user);
  }
```
불필요한 if문은 줄이죠!

2020-06-04 14:00 UTC, ksundong commented on BE/src/main/resources/application.yml
> +root: localhost:8080/
뒤에 /는 제거하는게 좋지않나요? 어떤 의도인지 잘 모르겠어요.

2020-06-04 14:00 UTC, ksundong commented on BE/src/test/java/kr/codesquad/airbnb11/controller/RoomRestControllerTest.java
> +@ContextConfiguration(classes = {JwtService.class})
음 제가 해결해서 커밋 해뒀었는데 다시 제거가 됬네요.

Context가 굳이 필요없어서 MockBean으로 가짜 Bean을 주입 받습니다.

2020-06-04 14:37 UTC, merged

2020-06-05 02:44 UTC, 102092 commented on BE/src/main/java/kr/codesquad/airbnb11/common/config/IntercepterConfig.java
> +}
Interceptor 가 jwtSerive , LoginService를 받아서 그런지
Web Configure에 넣어두면 순환 주입 오류(jwt -> interceptor -> webconfig -> jwt..) 가 나더라구여
그래서 불가피하게 분리하게 되었습니다.
혹시 생각나시는게 있으면 수정해보면 좋을 것 같아요!

2020-06-05 02:44 UTC, 102092 commented on BE/src/main/resources/application.yml
> +root: localhost:8080/
루트를 표현하고 싶었는데 생각해보니까 없어도 되긴 하겠네요..

2020-06-05 02:46 UTC, 102092 commented on BE/src/test/java/kr/codesquad/airbnb11/controller/RoomRestControllerTest.java
> +@ContextConfiguration(classes = {JwtService.class})
Interceptor에 login Service 를 통해 DB와 접근하는 로직이 있는데 
jwt , loginService를 mock으로 받으면, 그런것을 대신해주는 것인가봐요!
괜찮으시면 이 부분에 대해 좀 더 설명해주실 수 있나요???

2020-06-05 02:46 UTC, 102092 commented
제가 막힌 부분을 대신 해결해주셔서 감사합니다!
늦게 까지 하신것 같은데.. 고생하셨어요!