Feature/be/room people count
codesquad-member-2020/airbnb-11 pull request #59
Opened 2020-05-26 08:21 UTC by 102092

- controller -> service -> repository 구조는 아직 만들지 않았습니다.
- 검색 관련 기능1,2,3 들을 다 만든다음에, 합쳐보면 좋을것 같아요

2020-05-26 09:10 UTC, ksundong requested changes
고생하셨습니다. 리뷰 하면서 얘기를 했지만 ㅋㅋㅋ
확인부탁드려요!

2020-05-26 09:10 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/domain/room/Room.java
> +  private Integer id;
`@Id` 를 위로 올리신 이유가 있을까요?

2020-05-26 09:10 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/domain/room/Room.java
> +  }
이 생성자는 왜 필요한지 알 수 있을까요?

2020-05-26 09:10 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/domain/room/Room.java
> +    return new ToStringBuilder(this, ToStringStyle.SHORT_PREFIX_STYLE)
이건 무슨 옵션인지 알 수 있을까요?

2020-05-26 09:10 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/domain/room/Room.java
> +    }
빈 생성자를 한 줄로 쓰는 것은 어떨까요?

2020-05-26 09:10 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomRepository.java
> +  @Transactional(readOnly = true)
여기서 `@Transactional` 애노테이션이 필요한 이유가 있을까요?

2020-05-26 09:10 UTC, ksundong commented on BE/src/test/java/kr/codesquad/airbnb11/domain/room/RoomRepositoryTest.java
> +  @DisplayName("조건에 해당하는 방이 없을 때")
좀 더 명확하게 검색 조건에 해당하는 방이 없을 때가 좋을 것 같다는 의견입니다!

2020-05-26 09:10 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomRepository.java
> +  List<Room> findAllByMaxPersonCountIsLessThanEqual(int maxPersonCount);
MoreThan 아닐까요? 저희는 x명 이상을 원하는 것 같아요.

2020-05-26 09:10 UTC, ksundong commented on BE/src/test/java/kr/codesquad/airbnb11/domain/room/RoomRepositoryTest.java
> +  @DisplayName("8명 이하인 방 검색하기")
이 부분도 수정이 필요할 것 같아요!

2020-05-26 09:10 UTC, ksundong commented on BE/src/test/java/kr/codesquad/airbnb11/domain/room/RoomRepositoryTest.java
> +    Room r1 = Room.Builder.of()
builder of는 조금 어색한 느낌입니다!

2020-05-26 09:10 UTC, ksundong commented on BE/src/test/java/kr/codesquad/airbnb11/domain/room/RoomRepositoryTest.java
> +  void search_none() {
메소드명은 camelCase가 낫지 않을까요?
아니면 테스트 명을 한글로 적는편이 나을 것 같아요.

2020-05-26 09:10 UTC, ksundong commented on BE/src/test/resources/application.yml
> +    url: jdbc:h2:mem:testdb;
airbnb로도 되네요 ㅋㅋ

2020-05-26 15:28 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/domain/room/Room.java
> +    }
이거 관련해서는 Convention을 정하는 게 좋을 것 같습니다~

2020-05-27 01:54 UTC, 102092 commented on BE/src/main/java/kr/codesquad/airbnb11/domain/room/Room.java
> +  }
빌더에서 사용하고 있는 생성자 입니다

2020-05-27 01:55 UTC, 102092 commented on BE/src/main/java/kr/codesquad/airbnb11/domain/room/Room.java
> +    return new ToStringBuilder(this, ToStringStyle.SHORT_PREFIX_STYLE)
`toString` 시에 객체가 생성되는 메모리 주소를 뺀 나머지가 출력되는 옵션이에요!

2020-05-27 01:55 UTC, 102092 commented on BE/src/main/java/kr/codesquad/airbnb11/domain/room/Room.java
> +    }
ㅋㅋㅋ 어떤 방법이 편하신가요?
저는 생성자가 자동생성 시에는 위와 같이 되고 있습니다!!

2020-05-27 01:57 UTC, 102092 commented on BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomRepository.java
> +  @Transactional(readOnly = true)
생각해보니 딱히 없는듯해요

보통 `Service` 에 트랜잭션 어노테이션을 붙여주곤 했는데, 현재는 만들지 않아서 궁여지책으로 `Repository`에 붙였네요

`Select` 하는 메서드에는 트랜잭션을 붙일 필요가 없을까요?

2020-05-27 01:58 UTC, 102092 commented on BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomRepository.java
> +  List<Room> findAllByMaxPersonCountIsLessThanEqual(int maxPersonCount);
맞아요..ㅠㅠ 수정하겠습니다~

2020-05-27 01:58 UTC, 102092 commented on BE/src/test/java/kr/codesquad/airbnb11/domain/room/RoomRepositoryTest.java
> +    Room r1 = Room.Builder.of()
어제 보여주신 패턴으로 수정해볼게요!!

2020-05-27 01:58 UTC, 102092 commented on BE/src/test/java/kr/codesquad/airbnb11/domain/room/RoomRepositoryTest.java
> +  void search_none() {
한글명으로 바꿔보겠습니다!

2020-05-27 01:59 UTC, 102092 commented on BE/src/test/resources/application.yml
> +    url: jdbc:h2:mem:testdb;
그러게요ㅋㅋ 신기합니닼ㅋㅋ

2020-05-27 02:46 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/domain/room/Room.java
> +    }
일단 자동 포맷팅 되는 대로 맞추도록 하겠습니다!

2020-05-27 02:57 UTC, ksundong commented on BE/src/main/java/kr/codesquad/airbnb11/domain/room/RoomRepository.java
> +  @Transactional(readOnly = true)
제가 알기로는 `@Transactional`을 사용하는 경우가 이렇게 되는 것으로 알고 있어요.
기본적으로 JDBC의 경우 Auto Commit 옵션이 True로 되어있고, Transaction을 이용하려면 이 옵션을 false로 바꿔주어야 합니다.

그리고 false로 바꿔주면 transaction이 생성되게 되고, commit 또는 rollback이 발생할 때 까지 한 transaction에서 작업을 진행하게 됩니다. 작업중에 오류가 발생하게되면 rollback을 시키고, 이는 transaction이전의 상태로 되돌아감을 의미하는 것으로 알고 있어요.

그리고 보통 transaction은 여러 개의 쿼리를 한 작업으로 실행할 때, 사용하는 것이라서 여러개의 쿼리가 날아가지 않는다면 굳이 필요 없을 것 같다는 의견입니다!

2020-05-27 04:16 UTC, ksundong commented on BE/src/test/java/kr/codesquad/airbnb11/domain/room/RoomRepositoryTest.java
> +
굳이 여기에 빈 라인이 있을 필요는 없을 것 같습니다!

2020-05-27 04:17 UTC, ksundong commented
고생하셨습니다!

2020-05-27 04:17 UTC, merged